using System.Collections.Generic;

namespace RemotePunch.Web.Models
{
    /// <summary>What the punch page posts to Api/Punch.ashx.</summary>
    public class PunchRequest
    {
        public string RequestedType { get; set; }   // IN | OUT | AUTO
        public GeoFix Fix { get; set; }
        /// <summary>Idempotency key generated by the browser; replays return the first result.</summary>
        public string ClientRequestId { get; set; }
        public string DeviceSignals { get; set; }
        public string DeviceLabel { get; set; }
        public string Note { get; set; }
        public string SelfieBase64 { get; set; }
        /// <summary>Client-side integrity findings, e.g. a patched geolocation API.</summary>
        public List<string> ClientWarnings { get; set; }

        public PunchRequest()
        {
            ClientWarnings = new List<string>();
            RequestedType = "AUTO";
        }
    }
}
